# Generated by Django 4.2.1 on 2023-06-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ans_A',
            new_name='ans_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ans_B',
            new_name='ans_b',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ans_C',
            new_name='ans_c',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ans_D',
            new_name='ans_d',
        ),
    ]
